//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailSupplierGood
    {
        public int Id { get; set; }
        public string IdSupplier { get; set; }
        public string IdGoods { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> PurchaseTax { get; set; }
        public Nullable<double> PurchaseDiscount { get; set; }
        public Nullable<double> Inventory { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
