//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTransferOrder
    {
        public int Id { get; set; }
        public string IdGoods { get; set; }
        public Nullable<int> IdPuchaseOrder { get; set; }
        public string IdGood { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Amount1 { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> StatusExport { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
    }
}
