//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailSaleOrder
    {
        public int Id { get; set; }
        public string IdGoods { get; set; }
        public Nullable<int> IdSaleOrder { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Amount1 { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Tax { get; set; }
        public Nullable<double> PriceTax { get; set; }
        public Nullable<double> PriceDiscount { get; set; }
        public Nullable<double> SumPrice { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        public virtual SalesOrder SalesOrder1 { get; set; }
    }
}
