//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrder()
        {
            this.DetailGoodOrders = new HashSet<DetailGoodOrder>();
            this.DetailTransferOrders = new HashSet<DetailTransferOrder>();
            this.Receipts = new HashSet<Receipt>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdTypeStatus { get; set; }
        public Nullable<int> IdPayMethod { get; set; }
        public string IdWareHouse { get; set; }
        public string IdStore { get; set; }
        public string IdFromWareHouse { get; set; }
        public string IdSupplier { get; set; }
        public string Name { get; set; }
        public string IdGeneral { get; set; }
        public string IdInternal { get; set; }
        public Nullable<System.DateTime> DatePay { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<double> Sumprice { get; set; }
        public Nullable<double> Liabilities { get; set; }
        public Nullable<double> PartialPay { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailGoodOrder> DetailGoodOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailTransferOrder> DetailTransferOrders { get; set; }
        public virtual GeneralAccounting GeneralAccounting { get; set; }
        public virtual InternalAccounting InternalAccounting { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual Store Store { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual TypeStatu TypeStatu { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        public virtual WareHouse WareHouse1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
