//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportlEndShift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReportlEndShift()
        {
            this.DetailReportEndShifts = new HashSet<DetailReportEndShift>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdFirst { get; set; }
        public string IdUser { get; set; }
        public string IdStall { get; set; }
        public string IdStore { get; set; }
        public Nullable<int> IdNumShift { get; set; }
        public Nullable<double> FirstShiftMoney { get; set; }
        public Nullable<double> EndShiftMoney1 { get; set; }
        public Nullable<double> RealMoney { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailReportEndShift> DetailReportEndShifts { get; set; }
        public virtual NumberShift NumberShift { get; set; }
        public virtual ReportFirstShift ReportFirstShift { get; set; }
        public virtual Stall Stall { get; set; }
        public virtual Stall Stall1 { get; set; }
        public virtual Store Store { get; set; }
        public virtual User User { get; set; }
    }
}
