//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iGMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Bills = new HashSet<Bill>();
            this.ReportFirstShifts = new HashSet<ReportFirstShift>();
            this.ReportlEndShifts = new HashSet<ReportlEndShift>();
            this.SalesOrders = new HashSet<SalesOrder>();
        }
    
        public string Id { get; set; }
        public string User1 { get; set; }
        public string Pass { get; set; }
        public string Name { get; set; }
        public string AddRess { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Description { get; set; }
        public Nullable<int> RoleAdmin { get; set; }
        public Nullable<int> Role { get; set; }
        public string WorkingHour { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyBy { get; set; }
        public Nullable<bool> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bill> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportFirstShift> ReportFirstShifts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportlEndShift> ReportlEndShifts { get; set; }
        public virtual Role Role1 { get; set; }
        public virtual RoleAdmin RoleAdmin1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrder> SalesOrders { get; set; }
    }
}
